#!/usr/bin/env python
# coding: utf-8

import argparse
import sys

from feed2maildir import VERSION
from feed2maildir.converter import Converter
from feed2maildir.reader import Reader

def main():
    parser = argparse.ArgumentParser(description='Convert Feeds to a maildir',
                                     epilog='Feed2Maildir '+ VERSION)
    parser.add_argument('-m', metavar='<dir>',
                        help='maildir location')
    parser.add_argument('-n', metavar='<name>',
                        help='feed name')
    parser.add_argument('-s', action='store_true',
                        help='strip HTML from the feed content')
    args = vars(parser.parse_args())

    if args['m']:
        maildir = args['m']
    else:
        raise Exception("No maildir given")

    if args['n']:
        name = args['n']
    else:
        raise Exception("No feed name given")

    reader = Reader(sys.stdin.read())

    converter = Converter(maildir, name, strip=args['s'])
    converter.load(reader.feed)
    converter.run()

if __name__ == '__main__':
    main()
